import {useEffect,useState} from 'react';
import {admin} from '../services/admin';
const split=v=>v.split('|').map(x=>x.trim()).filter(Boolean);
export default function Admin(){
 const [form,setForm]=useState({title:'',body:'',question:'',options:'Yes|No',quizQ:'',quizOptions:'',correct:'',mediaTitle:'',mediaUrl:'',competition:'',teamId:'',team:'',playerId:'',player:'',fixtureId:'',homeId:'',awayId:'',kickoff:''});
 const [users,setUsers]=useState([]),[msg,setMsg]=useState('');
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const loadUsers=()=>admin.users().then(x=>setUsers(x.users||[])).catch(e=>setMsg(e.message));
 useEffect(()=>{loadUsers()},[]);
 async function run(fn,ok){try{await fn();setMsg(ok);loadUsers()}catch(e){setMsg(e.message)}}
 return <div className="page"><h1>Admin Dashboard</h1>{msg&&<p>{msg}</p>}
  <section className="card"><h2>Publish News</h2><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Title"/><textarea value={form.body} onChange={e=>set('body',e.target.value)} placeholder="Story"/><button className="btn" onClick={()=>run(()=>admin.news({title:form.title,body:form.body,published:true}),'News published')}>Publish</button></section>
  <section className="card"><h2>Create Poll</h2><input value={form.question} onChange={e=>set('question',e.target.value)} placeholder="Question"/><input value={form.options} onChange={e=>set('options',e.target.value)} placeholder="Option|Option"/><button className="btn" onClick={()=>run(()=>admin.poll({question:form.question,options:split(form.options),active:true}),'Poll created')}>Create</button></section>
  <section className="card"><h2>Create Quiz</h2><input value={form.quizQ} onChange={e=>set('quizQ',e.target.value)} placeholder="Question"/><input value={form.quizOptions} onChange={e=>set('quizOptions',e.target.value)} placeholder="Option|Option|Option"/><input value={form.correct} onChange={e=>set('correct',e.target.value)} placeholder="Correct answer"/><button className="btn" onClick={()=>run(()=>admin.quiz({question:form.quizQ,options:split(form.quizOptions),correct_answer:form.correct,published:true}),'Quiz published')}>Publish Quiz</button></section>
  <section className="card"><h2>Add Authorized Media</h2><input value={form.mediaTitle} onChange={e=>set('mediaTitle',e.target.value)} placeholder="Video title"/><input value={form.mediaUrl} onChange={e=>set('mediaUrl',e.target.value)} placeholder="YouTube/Vimeo HTTPS URL"/><button className="btn" onClick={()=>run(()=>admin.media({title:form.mediaTitle,url:form.mediaUrl,authorized:true}),'Media added')}>Add Media</button></section>
  <section className="card"><h2>Add Competition</h2><input value={form.competition} onChange={e=>set('competition',e.target.value)} placeholder="Competition name"/><button className="btn" onClick={()=>run(()=>admin.competition({name:form.competition,active:true}),'Competition added')}>Add Competition</button></section>
  <section className="card"><h2>Add Team</h2><input value={form.teamId} onChange={e=>set('teamId',e.target.value)} placeholder="API team ID"/><input value={form.team} onChange={e=>set('team',e.target.value)} placeholder="Team name"/><button className="btn" onClick={()=>run(()=>admin.team({api_team_id:Number(form.teamId),name:form.team}),'Team added')}>Add Team</button></section>
  <section className="card"><h2>Add Player</h2><input value={form.playerId} onChange={e=>set('playerId',e.target.value)} placeholder="API player ID"/><input value={form.player} onChange={e=>set('player',e.target.value)} placeholder="Player name"/><button className="btn" onClick={()=>run(()=>admin.player({api_player_id:Number(form.playerId),name:form.player}),'Player added')}>Add Player</button></section>
  <section className="card"><h2>Add Fixture</h2><input value={form.fixtureId} onChange={e=>set('fixtureId',e.target.value)} placeholder="API fixture ID"/><input value={form.homeId} onChange={e=>set('homeId',e.target.value)} placeholder="Home team API ID"/><input value={form.awayId} onChange={e=>set('awayId',e.target.value)} placeholder="Away team API ID"/><input type="datetime-local" value={form.kickoff} onChange={e=>set('kickoff',e.target.value)}/><button className="btn" onClick={()=>run(()=>admin.fixture({api_fixture_id:Number(form.fixtureId),home_team_api_id:Number(form.homeId),away_team_api_id:Number(form.awayId),kickoff_at:new Date(form.kickoff).toISOString()}),'Fixture added')}>Add Fixture</button></section>
  <section className="card"><h2>Users</h2>{users.map(u=><p key={u.id}>{u.username} · {u.role} · {u.is_online?'Online':'Offline'}</p>)}{!users.length&&<p>No users returned.</p>}</section>
 </div>
}
