import {Router} from 'express';
import {football} from '../services/football.js';
const r=Router();
const season=q=>Number(q.season||process.env.FOOTBALL_DEFAULT_SEASON||2026), league=q=>Number(q.league||39);
r.get('/fixtures',async(q,s,n)=>{try{s.json(await football.fixtures(league(q.query),season(q.query)))}catch(e){n(e)}});
r.get('/fixtures/live',async(q,s,n)=>{try{s.json(await football.live(league(q.query)))}catch(e){n(e)}});
r.get('/standings',async(q,s,n)=>{try{s.json(await football.standings(league(q.query),season(q.query)))}catch(e){n(e)}});
r.get('/teams',async(q,s,n)=>{try{s.json(await football.teams(league(q.query),season(q.query)))}catch(e){n(e)}});
r.get('/teams/:id',async(q,s,n)=>{try{s.json(await football.team(q.params.id))}catch(e){n(e)}});
r.get('/teams/:id/squad',async(q,s,n)=>{try{s.json(await football.squad(q.params.id))}catch(e){n(e)}});
r.get('/players/:id',async(q,s,n)=>{try{s.json(await football.player(q.params.id,season(q.query)))}catch(e){n(e)}});
r.get('/topscorers',async(q,s,n)=>{try{s.json(await football.topScorers(league(q.query),season(q.query)))}catch(e){n(e)}});
r.get('/topassists',async(q,s,n)=>{try{s.json(await football.topAssists(league(q.query),season(q.query)))}catch(e){n(e)}});
r.get('/matches/:id',async(q,s,n)=>{try{s.json(await football.match(q.params.id))}catch(e){n(e)}});
r.get('/matches/:id/events',async(q,s,n)=>{try{s.json(await football.events(q.params.id))}catch(e){n(e)}});
r.get('/matches/:id/statistics',async(q,s,n)=>{try{s.json(await football.statistics(q.params.id))}catch(e){n(e)}});
r.get('/matches/:id/lineups',async(q,s,n)=>{try{s.json(await football.lineups(q.params.id))}catch(e){n(e)}});
r.get('/leagues',async(q,s,n)=>{try{s.json(await football.leagues(q.query.country||'Kenya',q.query.season||''))}catch(e){n(e)}});
r.get('/seasons',async(q,s,n)=>{try{s.json(await football.seasons())}catch(e){n(e)}});
export default r;
